site_name: DiversityLens
theme:
  name: material
docs_dir: docs
plugins: 
- mkdocstrings:
    handlers:
      python:
        docstring_style: google
nav:
  - Home: index.md
  - API: API.md
  - About: about.md
  - License: license.md