site_name: DiversityLens
theme:
  name: material
  features:
    -navigation.tabs
    -search.suggest
    -versioning.switcher

docs_dir: docs
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]       
          options:
            show_source: false
            docstring_style: google 
            show_root_heading: true
nav:
  - Home: index.md
  - API: API.md
  - About: about.md
  - License: license.md

