name: Publish Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository     
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies for dlib
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Configure Git author.  # Necessary part to push the commits
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements_doc.txt

      - name: Expose src on PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE/src:$PYTHONPATH" >> $GITHUB_ENV

      - name: Deploy documentation with mike
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          if [ "${{ github.ref_name }}" = "feature_publish-mkdocs" ]; then
            echo "Deploying 'feature_publish-mkdocs' branch as 'latest'..."
            mike deploy --push latest
            mike set-default --push latest
          else
            echo "Deploying branch ${{ github.ref_name }} as ${{ github.ref_name }}..."
            mike deploy --push "${{ github.ref_name }}"
          fi
